export const GET_CURRENCY_LIST_START = "GET_CURRENCY_LIST_START";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_RATES_SUCCESS = "GET_CURRENCY_RATES_SUCCESS";
export const GET_CURRENCY_LIST_FAIL = "GET_CURRENCY_LIST_FAIL";

export const GET_RESULTS_START = "GET_RESULTS_START";
export const GET_RESULTS_SUCCESS = "GET_RESULTS_SUCCESS";
export const GET_RESULTS_FAIL = "GET_RESULTS_FAIL";